[devshell]
name = "monorepo"

packages = [ 
  "diffutils", # used by golangci-lint
  "nvfetcher"
]

[[commands]] # TODO: This is not working. Can't find flag "-f"??
help = "update a dependency (\"update golangci-lint\")"
name = "update"
command = "nvfetcher -f"

[[commands]]
help = "programming language"
package = "go_1_17"
category = "go"

[[commands]]
help = "linter"
package = "golangci-lint"
category = "go"

[[commands]]
help = "generate frugal"
package = "frugal"
category = "encoding"

[[commands]]
help = "manage edgedb"
name = "edgedb"
command = "docker-compose exec edgedb edgedb -I local_dev $@"
category = "edgedb"

[[commands]]
help = "migrate edgedb"
name = "migrate"
command = "edgedb migration create && edgedb migration apply"
category = "edgedb"
