#imports = [
  #"language.go"
#]

[devshell]
name = "monorepo"

packages = [ 
  "nvfetcher"
]

[[commands]] # TODO: This is not working. Can't find flag "-f"??
help = "update a dependency (\"update golangci-lint\")"
name = "update"
command = "nvfetcher -f"

[[commands]]
help = "run linting"
package = "golangci-lint"
category = "go"

[[commands]]
help = "generate frugal"
package = "frugal"
category = "encoding"
