#[go]
#fetch.github = "golang/go"
#src.manual = "go1.18beta1"

[nvfetcher]
fetch.github = "berberman/nvfetcher"
src.manual = "0.4.0"

[niv]
fetch.github = "nmattia/niv"
src.manual = "v0.2.19"

[golangci-lint]
fetch.github = "golangci/golangci-lint"
src.manual = "v1.43.0"

[frugal]
fetch.github = "Workiva/frugal"
src.manual = "v3.14.13"
