# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  frugal = {
    pname = "frugal";
    version = "v3.14.13";
    src = fetchFromGitHub ({
      owner = "Workiva";
      repo = "frugal";
      rev = "v3.14.13";
      fetchSubmodules = false;
      sha256 = "sha256-apX4MFzeR7+5gWauw5HXPK0c7N4uTSqkE2vqnYB5LJs=";
    });
  };
  golangci-lint = {
    pname = "golangci-lint";
    version = "v1.43.0";
    src = fetchFromGitHub ({
      owner = "golangci";
      repo = "golangci-lint";
      rev = "v1.43.0";
      fetchSubmodules = false;
      sha256 = "sha256-8aIKFLP1x9B5IMuyQ12LLIq79of4XwCdmDwae4T5MPg=";
    });
  };
  nvfetcher = {
    pname = "nvfetcher";
    version = "0.4.0";
    src = fetchFromGitHub ({
      owner = "berberman";
      repo = "nvfetcher";
      rev = "0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-XABvQUq2qv+YcQxW93DnU8mgtVsGJWyhcznny/Lbp0Q=";
    });
  };
}
